<?php

echo '<li><a href="'.$this->url->getApiUrl($class).'">'.$class.'</a>';

if($inheritance && isset($tree->inheritance[$class]))
{
	echo ' <span>extends ';
	echo stripos($tree->inheritance[$class], 'phalcon')===0
		? $this->tag->linkToApi($tree->inheritance[$class])
		: $tree->inheritance[$class];
	echo '</span>';
}

if($implementation && isset($tree->implementation[$class]))
{
	echo ' <span>implements ';
	$interfaces = [];
	foreach($tree->implementation[$class] as $interface)
	{
		$interfaces[] = stripos($interface, 'phalcon')===0
			? $this->tag->linkToApi($interface)
			: $interface;
	}
	echo join(', ', $interfaces), '</span> ';
}

if($children)
{
	$this->view->partial('classes-list-children', [
		'parent'         => $class,
		'inheritance'    => $inheritance,
		'implementation' => $implementation,
	]);
}

echo '</li>';